Upgrade to Ruby 3.x
manheim/eb_deployer pull request #3
Opened 2023-09-27 03:37 UTC by qwcode

2023-09-27 15:03 UTC, duckpuppy requested changes

2023-09-27 15:03 UTC, duckpuppy commented on eb_deployer.gemspec
The e-mail addresses and homepage in the gemspec are all from 5 years ago and should also be updated.

2023-09-27 16:30 UTC, duckpuppy approved these changes

2023-09-27 17:15 UTC, jeremiahlukus commented on .github/workflows/test.yml
> +    - uses: ruby/setup-ruby@52b8784594ec115fd17094752708121dc5dabb47
```
   - uses: ruby/setup-ruby@52b8784594ec115fd17094752708121dc5dabb47    
      with:
        bundler-cache: true
 ```
 
 I think this is faster

2023-09-27 21:17 UTC, qwcode commented on .github/workflows/test.yml
> +    - uses: ruby/setup-ruby@52b8784594ec115fd17094752708121dc5dabb47
ok, updated

2023-09-28 12:45 UTC, codezninja approved these changes
lgtm. Just had that one workflow change unless we plan on updating to main

2023-09-28 12:45 UTC, codezninja commented on .github/workflows/release.yml
> +      - main
```suggestion
      - master
```

unless we are planning on updating the repo to main

2023-10-17 01:12 UTC, qwcode commented on .github/workflows/release.yml
> +      - main
switched to master for now

2023-10-17 01:13 UTC, merged